name: fabrika_controll_app
version: 1.0.49+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  appwrite: 11.0.0
  flex_color_scheme: 7.3.1
  google_fonts: 6.1.0
  email_validator: 2.1.17
  line_icons: 2.0.3
  tab_container: 2.0.0
  intl: 0.18.1
  shared_preferences: ^2.2.2
  flutter_snake_navigationbar: 0.6.1
  flutter_keyboard_visibility: ^5.4.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  device_preview: 1.1.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

